version: '3.8'

services:
  app:
    container_name: spidex-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    env_file:
      - .env
    restart: unless-stopped